### ISSUE TITLE
java.lang.NullPointerException: Unexpected error on multiplayer server

### ISSUE THREAD

**Issue by Gregie** [Arcaratus/BloodArsenal#35]
I discovered that this mod happened to be the cause of a rather troublesome "S0FPacketSpawnMob.func_148833_a" error. Removing every mod one at a time until BloodArsenal remained. Anything I can do to fix it, or is this one of those SOL errors? I would very much like to add the mod back to the server when able!

Log:
http://pastebin.com/K3P78CWq

P.S.
The server doesn't crash, only the client.

**Comment by Arcaratus** [comment]
This bug has been reoccurring for awhile now, but I have no clue what causes it as none of the crash reports that people have sent me point to anything useful. I will try my best to resolve this though.

**Comment by Gregie** [comment]
A big Thank you for looking into the matter!

**Comment by Ricket** [comment]
Other reports here, but of course it's always the same stack trace, so maybe this isn't very helpful: http://support.feed-the-beast.com/t/ftb-horizons-daybreaker-1-2-0-playing-multiplayer-crashing-client/18576/2

**Comment by prenetic** [comment]
+1 to this issue under Horizons: Daybreaker 1.2.0. Not sure if this occurs in earlier versions of the pack since this was the first iteration we spun up for our group. Have not tested the affected world on single player, but on multiplayer with seed -1652592391245384371 we find ourselves crashing near coordinates x=222.00, y=88.17, z=-1716.38.

**Comment by Arcaratus** [comment]
You know, maybe it has something to do with my CommonProxy class
