### ISSUE TITLE
Drill of the dead does not accept the portable altar as a source

### ISSUE THREAD

**Issue by Boter316** [Arcaratus/BloodArsenal#45]
as the title states, I found this while talking to some peeps in the sanguimancy github, so I thought I'd post it here

**Comment by Arcaratus** [comment]
That's because in 1.7.10 most things that fill the altar search for the altar in BM, I cannot fix this on their end as such. They'd have to search explicitly for the Portable Altar on their end which, I'm almost absolutely sure no one would like to do. As of now, the Portable Altar can only be filled by liquid transfer methods (and maybe some others).
